spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ordersDb
    username: myUser
    password: myUser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true